# Generated by Django 2.2.6 on 2020-02-08 14:22

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Cake pops', 'Cake pops'), ('Chocolates', 'Chocolates'), ('Macarons', 'Macarons'), ('Pastries', 'Pastries'), ('Cookies', 'Cookies'), ('Cupcakes', 'Cupcakes'), ('Tarts', 'Tarts')], default='Cake pops', max_length=100)),
                ('photo', pyuploadcare.dj.models.ImageField(null=True)),
                ('tags', models.ManyToManyField(to='products.Tag')),
            ],
        ),
    ]
